### PR TITLE
Refactored function names to be more aligned with gdscript standards

### PR DESCRIPTION
**Pull request by Duroxxigar**
Just went through and renamed the functions and signals to be snake_case. I did this so it is more consistent with the rest of the API for Godot. I'm pretty sure I got everything.

### CODE REVIEW

**Comment by pixelriot** [comment]
The gdscript functions are aligned to the C++ methods of the GOG api since everyone using the api will need to know what happens on the GOG side.
I think it's a matter of preference. I'll ask the Godot community.

**Comment by pixelriot** [comment]
@Duroxxigar The GD community approves:
grafik
Thanks :)

**Comment by lekoder** [comment]
You do realize that it's no-longer compiling after this, right? Because you also renamed the functions that are supposed to be overriden in implementation.

**Comment by pixelriot** [comment]
> You do realize that it's no-longer compiling after this, right? Because you also renamed the functions that are supposed to be overriden in implementation.

I haven't had time to work on the project for a long time. Maybe at the end of the year. Sorry.
Feel free to jump on board.

**Pull request merged**
